import json,os
from pathlib import Path
p=Path(__file__).resolve().parent.parent/'design/bayou-crossing'
def get(name):return json.loads((p/name).read_text())
def put(name,data):(p/name).write_text(json.dumps(data,indent=2)+'\n')
prompts=get('prompts.json');prompts['turtle']='Use case: stylized-concept. Asset type: mesh-ready reference for a Blender-modeled rideable turtle in a modern immersive Frogger river game. One original broad-shelled river turtle, full uncropped silhouette, three-quarter front elevated studio view, broad domed stable olive green shell with distinct hexagonal scutes and fine natural ridges, small inquisitive head extended forward, four separately readable short webbed legs, tiny tail, damp mossy green skin, warm ochre shell edge, believable anatomical construction, polished animated-feature realism and restrained fine detail. The shell is approximately one meter wide at game scale and must read as a safe platform. Even soft studio lighting, neutral perspective, plain warm gray background, subtle contact shadow. No water, no rocks, no frogs, no other turtles, no scenery, no text, no watermark, no cropped or floating parts.';put('prompts.json',prompts)
brief=get('room-brief.json');brief.update(purpose='Second playable arcade cabinet: Frogger-inspired road and river crossing with five homes and three escalating rounds.',runtimeSurface='Existing Three.js/Vite arcade; desktop elevated follow camera with optional frog-eye view; WebXR frog-eye camera.',boundsMeters=[22,8,25],hero={'id':'frog','role':'Playable frog with an unobscured landing area and readable next lane','reservedBoundsMeters':[1.3,1.5,1.3]},symmetry={'mode':'bilateral','order':2,'appliesTo':['architecture','barriers','circulation','repeatedProps'],'exceptions':['Moving traffic and floating platforms deliberately have asymmetric phases and directions.','Organic bank vegetation varies within symmetric placement envelopes.','Arcade cabinet occupies the right VECTOR bay; Brickstorm remains in the central bay.']},circulation={'description':'Direct cabinet entry onto a 3.4 m wide safe bank. Thirteen discrete rows: start, five traffic lanes, safe median, five river lanes, five home pads. Continuous side berms contain play.','minimumClearanceMeters':1.3},productionCamera={'viewport':[1280,720],'location':[0,6,5],'target':[0,0,-6],'verticalFovDegrees':52},performanceBudget={'maxSceneTriangles':250000,'maxVLowBytes':8000000,'maxHighTextureBytes':16000000},creditBudget={'maximumCredits':0,'approvalRequired':True},artifacts={'floorPlan':'plans/lower-room.png','reflectedCeilingPlan':'plans/reflected-ceiling.png','planMetadata':'plan-metadata.json','wallElevations':['plans/side-elevation.png'],'visualTarget':'plans/visual-target.png','openingContactSheet':'masks/opening-schedule.html'})
brief['functionalExceptions']=['Outdoor gameplay area: terrain substrate has thickness, but no roof or enclosing walls are proposed. Side berms provide explicit collision containment.','Arrival is a cabinet portal to a visible open bank, not a decorative architectural doorway.','Use Blender-authored geometry and built-in generated references; do not submit to a paid image-to-3D provider. This exception is pending user review.'];put('room-brief.json',brief)
props=get('props.json');props['generation']['enabled']=False;props['generation']['creditsPerTexturedTask']=None;props['generation']['hardCreditCeiling']=0;props['generation']['pricingVerifiedAt']='';props['authoring']={'provider':'local Blender 4.5.12','mode':'procedural geometry guided by generated references','status':'proposed; awaiting Function approval','paidProviderSpend':0}
assets=[]
for id,role,desc,dims,front,poly,count in [('frog','Player hero','Jade tree frog with four articulated limbs, amber eyes and webbed toes.',[.7,.5,.8],'negative-z',16000,1),('truck','Moving collision hazard','Teal pickup with separate wheels, cab, bed, lamps, glass and trim.',[2.8,1.5,1.05],'positive-x',10000,5),('log','Rideable river platform','Cypress log with bark ridges, end grain and stable riding surface.',[3.1,.76,.76],'positive-x',5000,9),('turtle','Rideable periodic diving platform','Olive shell with scutes, separate head and webbed legs.',[.9,.45,1.0],'negative-z',6500,18)]:
 assets.append({'id':id,'function':role,'description':desc,'class':'hero' if id=='frog' else 'reusable','dimensionsMeters':dims,'attachmentFace':'floor' if id in ['frog','truck'] else 'freestanding','semanticFront':front,'targetPolycount':poly,'intendedInstances':count,'rejectionCriteria':['Cropped or incomplete silhouette','Unclear or fused support and contact geometry','Primary visual shape does not match the approved reference','Target polygon budget exceeded by more than 20 percent'],'image':{'prompt':prompts[id],'generator':'built-in image_gen','source':'images/'+id+'.png','approved':False,'approvedBy':''},'attempts':[],'acceptedMesh':None})
props['assets']=assets;put('props.json',props)
layout=get('room-layout.json');layout['surfaces']=[{'id':'terrain','type':'ground','center':[0,-.35,-7.8],'dimensions':[22,.6,25]},{'id':'left-berm','type':'boundary','center':[-7.8,.18,-7.8],'dimensions':[.6,.4,18]},{'id':'right-berm','type':'boundary','center':[7.8,.18,-7.8],'dimensions':[.6,.4,18]}];layout['instances']=[{'id':'frog-player','assetId':'frog','position':[0,0,0]}]
for row in range(1,6):layout['instances'].append({'id':'truck-'+str(row),'assetId':'truck','position':[(-4.5+row*1.6)%8-4,0,-row*1.3]})
for row in [7,9,11]:
 for i,x in enumerate([-5,0,5]):layout['instances'].append({'id':f'log-{row}-{i}','assetId':'log','position':[x,.12,-row*1.3]})
for row in [8,10]:
 for i,x in enumerate([-5,0,5]):
  for j,dx in enumerate([-.75,0,.75]):layout['instances'].append({'id':f'turtle-{row}-{i}-{j}','assetId':'turtle','position':[x+dx,.12,-row*1.3]})
layout['productionCamera']=brief['productionCamera'];layout['sourceStudy']='meshes/layout-study.blend';layout['runtimeLaneSpecification']='../../src/games/bayou/engine.js';put('room-layout.json',layout)
op=get('openings.json');op['primaryArrival']={'openingId':'','exception':'Direct spatial cabinet transition to an open-air safe bank, 3.4 m wide and 1.3 m deep. No architectural doorway, cut wall, or roof is present.'};op['openings']=[];put('openings.json',op)
plan=get('plan-metadata.json');plan['coverage']=['room-outline','cutouts','openings','exterior-apron','main-sign','ingress-props','floor-markers','barriers','columns','circulation','placed-features'];plan['notes']={'cutouts':'None; no structural openings proposed','openings':'Direct portal arrival exception; no roof or wall','main-sign':'Cabinet marquee in existing right-hand arcade bay; not inside outdoor course','columns':'Boundary bollards and roadside lamp supports only','ceiling':'Open sky; reflected layer contains lamp booms only','source':'plans/provenance.json','coordinateConversion':'Engineering Blender +Y lane progression maps to runtime -Z'};plan['rows']=[{'row':r,'purpose':'start bank' if r==0 else 'traffic' if r<6 else 'safe median' if r==6 else 'river platforms' if r<12 else 'five lily homes'} for r in range(13)];put('plan-metadata.json',plan)
reviews=get('milestone-reviews.json');reviews['function']['evidence']=['review.html','plans/lower-room.png','plans/reflected-ceiling.png','plans/visual-target.png','images/contact-sheet.html'];reviews['function']['strangestElement']='River turtles are deliberately oversized and rideable; their scale is a gameplay promise, not natural-history realism.';reviews['function']['notes']='Await explicit approval of layout and all four reference images. Also request a Blender-only exception to the paid Meshy-specific portions of the bundled validator.';put('milestone-reviews.json',reviews)
report=get('final-report.json');report['postmortem']['remainingRisks']=['Function and Form approvals pending.','Blender MCP tools unavailable in this session.','game-dev executable not installed or available on PATH.','Bundled room validator requires a positive Meshy spend ceiling and accepted Meshy jobs, even for Blender-only authoring. Do not fabricate pricing or paid task receipts.'];put('final-report.json',report)
(p/'masks/opening-schedule.html').write_text('<!doctype html><title>Opening schedule</title><h1>No architectural openings proposed</h1><p>This outdoor crossing arrives through a cabinet transition onto a 3.4 m wide open bank. There are no walls, doorways, arches, or ceilings to cut. Side berms contain player movement.</p><img src="no-architectural-openings.png" alt="Empty architectural opening mask">')
